% Формирование сводной таблицы результатов
function print_results_table(U, buses, flows, branches, S_base)
  n = length(buses);
  fprintf('\n=== РЕЗУЛЬТАТЫ ПО УЗЛАМ ===\n');
  fprintf('%4s %6s %8s %8s %10s %10s\n', ...
    'Узел', 'Тип', 'U, о.е.', 'd, град', 'P, МВт', 'Q, Мвар');
  for i = 1:n
    fprintf('%4d %6s %8.4f %8.3f %10.2f %10.2f\n', ...
      i, buses(i).type, abs(U(i)), angle(U(i))*180/pi, ...
      -buses(i).P * S_base, -buses(i).Q * S_base);
  end

  fprintf('\n=== РЕЗУЛЬТАТЫ ПО ВЕТВЯМ ===\n');
  fprintf('%4s %3s-%3s %10s %10s %10s %10s %8s\n', ...
    'Ветвь', 'Нач', 'Кон', 'P_нач', 'Q_нач', 'dP', 'dQ');
  for l = 1:length(branches)
    fprintf('%4d %3d-%3d %10.3f %10.3f %8.4f %8.4f\n', ...
      l, branches(l).from, branches(l).to, ...
      real(flows(l).S_from)*S_base, imag(flows(l).S_from)*S_base, ...
      real(flows(l).dS)*S_base, imag(flows(l).dS)*S_base);
  end
end
